server:
    port: 8080

spring:
    application:
        name: task

    datasource:
        url: jdbc:mysql://localhost:3306/task
        username: root
        password: test123

    jpa:
        hibernate:
            ddl-auto: update